export const strings = {
  en: {
    appTitle: 'SprawlForge',
    toolTitle: 'Sector Generator',
    knobs: {
      seed: 'Seed',
      pack: 'Flavor pack',
      theme: 'Theme',
      reroll: 'Reroll',
      update: 'Update',
      dice: '🎲',
      diceLabel: 'New random seed, keep tags',
      showPois: 'Show POIs',
    },
    overlay: {
      generating: 'Generating…',
    },
    tagGroups: {
      terrain: 'Terrain',
      size: 'Size',
      density: 'Density',
      power: 'Power',
      activity: 'Activity',
      streets: 'Streets',
      water: 'Water',
    },
    tags: {
      inland: 'Inland',
      coastal: 'Coastal',
      bay: 'Bay',
      river: 'River',
      lakes: 'Lakes',
      islands: 'Islands',
      small: 'Small',
      medium: 'Medium',
      large: 'Large',
      sparse: 'Sparse',
      dense: 'Dense',
      packed: 'Packed',
      'corp-run': 'Corp-run',
      balanced: 'Balanced',
      fringe: 'Fringe',
      quiet: 'Quiet',
      normal: 'Normal',
      lively: 'Lively',
      planned: 'Planned',
      mixed: 'Mixed',
      sprawl: 'Sprawl',
      piers: 'Piers',
      piersNeedsWater: 'Needs water — pick a wet terrain',
    },
    exports: {
      svg: 'Export SVG',
      png: 'Export PNG',
      pdf: 'Export PDF',
    },
    crash: {
      title: 'SprawlForge hit an error and stopped.',
      hint: 'Reload the page to continue. If it keeps happening, please report the message below.',
    },
  },
}

export const t = strings.en
